"""empty message

Revision ID: 166b64ae8174
Revises: 28a4272095dc
Create Date: 2015-11-22 09:23:47.812000

"""

# revision identifiers, used by Alembic.
revision = '166b64ae8174'
down_revision = '28a4272095dc'

from alembic import op
import sqlalchemy as sa
import geoalchemy2 



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.drop_index('ix_Stream_point', table_name='Stream')
    op.drop_index('ix_Stream_lat', table_name='Stream')
    op.drop_index('ix_Stream_long', table_name='Stream')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_Stream_point', 'Stream', ['point'], unique=False)
    """op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )"""
    ### end Alembic commands ###
