"""empty message

Revision ID: 28a4272095dc
Revises: None
Create Date: 2015-11-01 10:16:15.351000

"""

# revision identifiers, used by Alembic.
revision = '28a4272095dc'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('ath_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('api_code', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Athlete_ath_id'), 'Athlete', ['ath_id'], unique=True)
    op.create_index(op.f('ix_Athlete_data_source'), 'Athlete', ['data_source'], unique=False)
    op.create_table('Activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ath_id', sa.Integer(), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('act_type', sa.String(length=20), nullable=True),
    sa.Column('act_name', sa.String(length=200), nullable=True),
    sa.Column('act_description', sa.String(length=500), nullable=True),
    sa.Column('act_startDate', sa.DateTime(), nullable=True),
    sa.Column('act_dist', sa.Float(precision=4), nullable=True),
    sa.Column('act_totalElevGain', sa.Float(precision=4), nullable=True),
    sa.ForeignKeyConstraint(['ath_id'], ['Athlete.ath_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Activity_act_id'), 'Activity', ['act_id'], unique=True)
    op.create_index(op.f('ix_Activity_act_startDate'), 'Activity', ['act_startDate'], unique=False)
    op.create_index(op.f('ix_Activity_act_type'), 'Activity', ['act_type'], unique=False)
    op.create_index(op.f('ix_Activity_ath_id'), 'Activity', ['ath_id'], unique=False)
    op.create_table('Stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(precision=8), nullable=True),
    sa.Column('long', sa.Float(precision=8), nullable=True),
    sa.Column('elapsed_time', sa.Float(precision=4), nullable=True),
    sa.Column('elapsed_dist', sa.Float(precision=4), nullable=True),
    sa.Column('velocity_smooth', sa.Float(precision=4), nullable=True),
    sa.Column('altitude', sa.Float(precision=4), nullable=True),
    sa.Column('grade_smooth', sa.Float(precision=4), nullable=True),
    sa.Column('watts', sa.Float(precision=4), nullable=True),
    sa.Column('temp', sa.Float(precision=4), nullable=True),
    sa.Column('heartrate', sa.Float(precision=4), nullable=True),
    sa.Column('cadence', sa.Float(precision=4), nullable=True),
    sa.Column('moving', sa.Boolean(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['Activity.act_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Stream_act_id'), 'Stream', ['act_id'], unique=False)
    op.create_index(op.f('ix_Stream_lat'), 'Stream', ['lat'], unique=False)
    op.create_index(op.f('ix_Stream_long'), 'Stream', ['long'], unique=False)
    op.create_index(op.f('ix_Stream_point'), 'Stream', ['point'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Stream_point'), table_name='Stream')
    op.drop_index(op.f('ix_Stream_long'), table_name='Stream')
    op.drop_index(op.f('ix_Stream_lat'), table_name='Stream')
    op.drop_index(op.f('ix_Stream_act_id'), table_name='Stream')
    op.drop_table('Stream')
    op.drop_index(op.f('ix_Activity_ath_id'), table_name='Activity')
    op.drop_index(op.f('ix_Activity_act_type'), table_name='Activity')
    op.drop_index(op.f('ix_Activity_act_startDate'), table_name='Activity')
    op.drop_index(op.f('ix_Activity_act_id'), table_name='Activity')
    op.drop_table('Activity')
    op.drop_index(op.f('ix_Athlete_data_source'), table_name='Athlete')
    op.drop_index(op.f('ix_Athlete_ath_id'), table_name='Athlete')
    op.drop_table('Athlete')
    ### end Alembic commands ###
