"""empty message

Revision ID: 30164533e1a1
Revises: 282e88dc4e85
Create Date: 2015-10-28 19:09:44.833000

"""

# revision identifiers, used by Alembic.
revision = '30164533e1a1'
down_revision = '282e88dc4e85'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.drop_index('ix_Athlete_ath_id', table_name='Athlete')
    op.create_index(op.f('ix_Athlete_ath_id'), 'Athlete', ['ath_id'], unique=True)

    op.drop_index('ix_Activity_act_id', table_name='Activity')
    op.create_index(op.f('ix_Activity_act_id'), 'Activity', ['act_id'], unique=True)

    op.create_foreign_key(None, 'Activity', 'Athlete', ['ath_id'], ['ath_id'])
    op.create_foreign_key(None, 'Stream', 'Activity', ['act_id'], ['act_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Stream', type_='foreignkey')
    op.create_index('idx_Stream_point', 'Stream', ['point'], unique=False)
    op.drop_index(op.f('ix_Athlete_ath_id'), table_name='Athlete')
    op.create_index('ix_Athlete_ath_id', 'Athlete', ['ath_id'], unique=False)
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    op.drop_index(op.f('ix_Activity_act_id'), table_name='Activity')
    op.create_index('ix_Activity_act_id', 'Activity', ['act_id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    ### end Alembic commands ###
