"""empty message

Revision ID: 33fec8aa1b6
Revises: 451089d48280
Create Date: 2016-04-03 10:03:16.338000

"""

# revision identifiers, used by Alembic.
revision = '33fec8aa1b6'
down_revision = '451089d48280'

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy_utils import URLType



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Segment',
    sa.Column('seg_id', sa.BigInteger(), nullable=False),
    sa.Column('last_updated_datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('act_type', sa.String(length=20), nullable=True),
    sa.Column('ath_cnt', sa.BigInteger(), nullable=True),
    sa.Column('cat', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(precision=4), nullable=True),
    sa.Column('effort_cnt', sa.BigInteger(), nullable=True),
    sa.Column('elev_gain', sa.Float(precision=4), nullable=True),
    sa.Column('elev_high', sa.Float(precision=4), nullable=True),
    sa.Column('elev_low', sa.Float(precision=4), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('seg_points', sa.Text(), nullable=True),
    sa.Column('start_point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('end_point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('seg_id')
    )
    op.create_index(op.f('ix_Segment_act_type'), 'Segment', ['act_type'], unique=False)
    op.create_index(op.f('ix_Segment_cat'), 'Segment', ['cat'], unique=False)
    op.create_index(op.f('ix_Segment_date_created'), 'Segment', ['date_created'], unique=False)
    op.create_index(op.f('ix_Segment_distance'), 'Segment', ['distance'], unique=False)
    op.create_index(op.f('ix_Segment_elev_gain'), 'Segment', ['elev_gain'], unique=False)
    op.create_index(op.f('ix_Segment_end_point'), 'Segment', ['end_point'], unique=False)
    op.create_index(op.f('ix_Segment_start_point'), 'Segment', ['start_point'], unique=False)
    """op.create_table('Stream_Act',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ath_id', sa.Integer(), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('act_name', sa.String(length=200), nullable=True),
    sa.Column('linestring', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.Column('multipoint', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT'), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['Activity.act_id'], ),
    sa.ForeignKeyConstraint(['ath_id'], ['Athlete.ath_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Stream_Act_act_id'), 'Stream_Act', ['act_id'], unique=False)
    op.create_index(op.f('ix_Stream_Act_ath_id'), 'Stream_Act', ['ath_id'], unique=False)
    op.create_index(op.f('ix_Stream_Act_linestring'), 'Stream_Act', ['linestring'], unique=False)
    op.create_index(op.f('ix_Stream_Act_multipoint'), 'Stream_Act', ['multipoint'], unique=False)
    op.drop_table('Stream_LineString')
    op.drop_table('spatial_ref_sys')"""
    op.add_column('Athlete', sa.Column('city', sa.String(), nullable=True))
    op.add_column('Athlete', sa.Column('country', sa.String(), nullable=True))
    op.add_column('Athlete', sa.Column('date_preference', sa.String(), nullable=True))
    op.add_column('Athlete', sa.Column('email', sa.String(), nullable=True))
    op.add_column('Athlete', sa.Column('email_language', sa.String(), nullable=True))
    op.add_column('Athlete', sa.Column('measurement_preference', sa.String(), nullable=True))
    op.add_column('Athlete', sa.Column('profile', sa.String(), nullable=True))
    op.add_column('Athlete', sa.Column('profile_medium', sa.String(), nullable=True))
    op.add_column('Athlete', sa.Column('state', sa.String(), nullable=True))
    """
    op.create_index(op.f('ix_Stream_point'), 'Stream', ['point'], unique=False)
    op.drop_index('idx_Stream_point', table_name='Stream')
    """
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_index('idx_Stream_point', 'Stream', ['point'], unique=False)
    op.drop_index(op.f('ix_Stream_point'), table_name='Stream')
    """
    op.drop_column('Athlete', 'state')
    op.drop_column('Athlete', 'profile_medium')
    op.drop_column('Athlete', 'profile')
    op.drop_column('Athlete', 'measurement_preference')
    op.drop_column('Athlete', 'email_language')
    op.drop_column('Athlete', 'email')
    op.drop_column('Athlete', 'date_preference')
    op.drop_column('Athlete', 'country')
    op.drop_column('Athlete', 'city')
    """op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )"""
    """op.create_table('Stream_LineString',
    sa.Column('ath_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('act_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('act_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('linestring', geoalchemy2.types.Geometry(), autoincrement=False, nullable=True)
    )"""
    op.drop_index(op.f('ix_Stream_Act_multipoint'), table_name='Stream_Act')
    op.drop_index(op.f('ix_Stream_Act_linestring'), table_name='Stream_Act')
    op.drop_index(op.f('ix_Stream_Act_ath_id'), table_name='Stream_Act')
    op.drop_index(op.f('ix_Stream_Act_act_id'), table_name='Stream_Act')
    op.drop_table('Stream_Act')
    op.drop_index(op.f('ix_Segment_start_point'), table_name='Segment')
    op.drop_index(op.f('ix_Segment_end_point'), table_name='Segment')
    op.drop_index(op.f('ix_Segment_elev_gain'), table_name='Segment')
    op.drop_index(op.f('ix_Segment_distance'), table_name='Segment')
    op.drop_index(op.f('ix_Segment_date_created'), table_name='Segment')
    op.drop_index(op.f('ix_Segment_cat'), table_name='Segment')
    op.drop_index(op.f('ix_Segment_act_type'), table_name='Segment')
    op.drop_table('Segment')
    ### end Alembic commands ###
