"""empty message

Revision ID: 451089d48280
Revises: 4e93ba4584f9
Create Date: 2016-01-04 20:52:54.655000

"""

# revision identifiers, used by Alembic.
revision = '451089d48280'
down_revision = '4e93ba4584f9'

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy_utils import URLType



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('ath_id', sa.Integer(), nullable=True),
    sa.Column('ath_fact_id', sa.Integer(), nullable=True),
    sa.Column('order_placed_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_method', sa.String(), nullable=True),
    sa.Column('paid_id', sa.Integer(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('order_supplier_placed', sa.Boolean(), nullable=True),
    sa.Column('order_supplier_placed_date', sa.DateTime(), nullable=True),
    sa.Column('order_supplier_shipped', sa.Boolean(), nullable=True),
    sa.Column('order_supplier_shipped_date', sa.DateTime(), nullable=True),
    sa.Column('order_closed', sa.Boolean(), nullable=True),
    sa.Column('order_closed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ath_fact_id'], ['Athlete_Fact.id'], ),
    sa.ForeignKeyConstraint(['ath_id'], ['Athlete.ath_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_Orders_ath_fact_id'), 'Orders', ['ath_fact_id'], unique=False)
    op.create_index(op.f('ix_Orders_ath_id'), 'Orders', ['ath_id'], unique=False)
    op.create_index(op.f('ix_Orders_order_placed_date'), 'Orders', ['order_placed_date'], unique=False)
    """op.drop_table('spatial_ref_sys')
    op.create_index(op.f('ix_Stream_point'), 'Stream', ['point'], unique=False)
    op.drop_index('idx_Stream_point', table_name='Stream')
    op.drop_index('idx_Stream_Act_linestring', table_name='Stream_Act')
    op.drop_index('idx_Stream_Act_multipoint', table_name='Stream_Act')"""
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_index('idx_Stream_Act_multipoint', 'Stream_Act', ['multipoint'], unique=False)
    op.create_index('idx_Stream_Act_linestring', 'Stream_Act', ['linestring'], unique=False)
    op.create_index('idx_Stream_point', 'Stream', ['point'], unique=False)
    op.drop_index(op.f('ix_Stream_point'), table_name='Stream')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )"""
    op.drop_index(op.f('ix_Orders_order_placed_date'), table_name='Orders')
    op.drop_index(op.f('ix_Orders_ath_id'), table_name='Orders')
    op.drop_index(op.f('ix_Orders_ath_fact_id'), table_name='Orders')
    op.drop_table('Orders')
    ### end Alembic commands ###
