"""empty message

Revision ID: 4e93ba4584f9
Revises: 26da869b8d3d
Create Date: 2015-12-30 11:30:33.310000

"""

# revision identifiers, used by Alembic.
revision = '4e93ba4584f9'
down_revision = '26da869b8d3d'

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy_utils import URLType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Athlete_Fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objecttypeid', sa.String(), nullable=True),
    sa.Column('ath_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('url', URLType(), nullable=True),
    sa.Column('exp_datetime_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ath_id'], ['Athlete.ath_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Athlete_Fact_ath_id'), 'Athlete_Fact', ['ath_id'], unique=False)
    op.create_index(op.f('ix_Athlete_Fact_objecttypeid'), 'Athlete_Fact', ['objecttypeid'], unique=False)
    """op.drop_table('spatial_ref_sys')
    op.create_index(op.f('ix_Stream_point'), 'Stream', ['point'], unique=False)
    op.drop_index('idx_Stream_point', table_name='Stream')
    op.drop_index('idx_Stream_Act_linestring', table_name='Stream_Act')
    op.drop_index('idx_Stream_Act_multipoint', table_name='Stream_Act')"""
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_index('idx_Stream_Act_multipoint', 'Stream_Act', ['multipoint'], unique=False)
    op.create_index('idx_Stream_Act_linestring', 'Stream_Act', ['linestring'], unique=False)
    op.create_index('idx_Stream_point', 'Stream', ['point'], unique=False)
    op.drop_index(op.f('ix_Stream_point'), table_name='Stream')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )"""
    op.drop_index(op.f('ix_Athlete_Fact_objecttypeid'), table_name='Athlete_Fact')
    op.drop_index(op.f('ix_Athlete_Fact_ath_id'), table_name='Athlete_Fact')
    op.drop_table('Athlete_Fact')
    ### end Alembic commands ###
