"""empty message

Revision ID: 83c5499c55ed
Revises: ea6e31908728
Create Date: 2016-05-24 07:42:11.917000

"""

# revision identifiers, used by Alembic.
revision = '83c5499c55ed'
down_revision = 'ea6e31908728'

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy_utils import URLType

from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column('Activity', sa.Column('act_achievement_count', sa.Integer(), nullable=True))
    op.add_column('Activity', sa.Column('act_athlete_count', sa.Integer(), nullable=True))
    op.add_column('Activity', sa.Column('act_avg_cadence', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_avg_heartrate', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_avg_speed', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_avg_temp', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_avg_watts', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_calories', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_comment_count', sa.Integer(), nullable=True))
    op.add_column('Activity', sa.Column('act_commute', sa.Boolean(), nullable=True))
    op.add_column('Activity', sa.Column('act_device_name', sa.String(), nullable=True))
    op.add_column('Activity', sa.Column('act_device_watts', sa.Boolean(), nullable=True))
    op.add_column('Activity', sa.Column('act_distance', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_elapsed_time', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_elev_high', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_elev_low', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_end_point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('Activity', sa.Column('act_gear_id', sa.String(), nullable=True))
    op.add_column('Activity', sa.Column('act_has_heartrate', sa.Boolean(), nullable=True))
    op.add_column('Activity', sa.Column('act_kilojoules', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_kudos_count', sa.Integer(), nullable=True))
    op.add_column('Activity', sa.Column('act_manual', sa.Boolean(), nullable=True))
    op.add_column('Activity', sa.Column('act_max_heartrate', sa.Integer(), nullable=True))
    op.add_column('Activity', sa.Column('act_max_speed', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_max_watts', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_moving_time', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_norm_power', sa.Float(precision=4), nullable=True))
    op.add_column('Activity', sa.Column('act_photo_url_list', postgresql.JSON(), nullable=True))
    op.add_column('Activity', sa.Column('act_private', sa.Boolean(), nullable=True))
    op.add_column('Activity', sa.Column('act_segment_efforts', postgresql.JSON(), nullable=True))
    op.add_column('Activity', sa.Column('act_start_point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('Activity', sa.Column('act_total_photo_count', sa.Integer(), nullable=True))
    op.add_column('Activity', sa.Column('act_trainer', sa.Boolean(), nullable=True))
    op.add_column('Activity', sa.Column('act_workout_type', sa.Integer(), nullable=True))

def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Activity', 'act_workout_type')
    op.drop_column('Activity', 'act_trainer')
    op.drop_column('Activity', 'act_total_photo_count')
    op.drop_column('Activity', 'act_start_point')
    op.drop_column('Activity', 'act_segment_efforts')
    op.drop_column('Activity', 'act_private')
    op.drop_column('Activity', 'act_photo_url_list')
    op.drop_column('Activity', 'act_norm_power')
    op.drop_column('Activity', 'act_moving_time')
    op.drop_column('Activity', 'act_max_watts')
    op.drop_column('Activity', 'act_max_speed')
    op.drop_column('Activity', 'act_max_heartrate')
    op.drop_column('Activity', 'act_manual')
    op.drop_column('Activity', 'act_kudos_count')
    op.drop_column('Activity', 'act_kilojoules')
    op.drop_column('Activity', 'act_has_heartrate')
    op.drop_column('Activity', 'act_gear_id')
    op.drop_column('Activity', 'act_end_point')
    op.drop_column('Activity', 'act_elev_low')
    op.drop_column('Activity', 'act_elev_high')
    op.drop_column('Activity', 'act_elapsed_time')
    op.drop_column('Activity', 'act_distance')
    op.drop_column('Activity', 'act_device_watts')
    op.drop_column('Activity', 'act_device_name')
    op.drop_column('Activity', 'act_commute')
    op.drop_column('Activity', 'act_comment_count')
    op.drop_column('Activity', 'act_calories')
    op.drop_column('Activity', 'act_avg_watts')
    op.drop_column('Activity', 'act_avg_temp')
    op.drop_column('Activity', 'act_avg_speed')
    op.drop_column('Activity', 'act_avg_heartrate')
    op.drop_column('Activity', 'act_avg_cadence')
    op.drop_column('Activity', 'act_athlete_count')
    op.drop_column('Activity', 'act_achievement_count')

    ### end Alembic commands ###
