"""empty message

Revision ID: ea6e31908728
Revises: f54a126b727
Create Date: 2016-05-21 12:48:53.333000

"""

# revision identifiers, used by Alembic.
revision = 'ea6e31908728'
down_revision = 'f54a126b727'

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy_utils import URLType

from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_table('Stream_Act',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ath_id', sa.Integer(), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('act_name', sa.String(), nullable=True),
    sa.Column('linestring', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.Column('multipoint', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT'), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['Activity.act_id'], ),
    sa.ForeignKeyConstraint(['ath_id'], ['Athlete.ath_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Stream_Act_act_id'), 'Stream_Act', ['act_id'], unique=False)
    op.create_index(op.f('ix_Stream_Act_ath_id'), 'Stream_Act', ['ath_id'], unique=False)
    op.create_index(op.f('ix_Stream_Act_linestring'), 'Stream_Act', ['linestring'], unique=False)
    op.create_index(op.f('ix_Stream_Act_multipoint'), 'Stream_Act', ['multipoint'], unique=False)
    op.drop_table('Stream_HeatPoint')
    op.drop_table('Stream_LineString')
    op.drop_table('spatial_ref_sys')"""
    op.add_column('Activity', sa.Column('polyline', sa.Text(), nullable=True))
    """
    op.create_index(op.f('ix_Activity_polyline'), 'Activity', ['polyline'], unique=False)
    op.drop_index('idx_Segment_end_point', table_name='Segment')
    op.drop_index('idx_Segment_start_point', table_name='Segment')
    op.drop_index('ix_Segment_act_type', table_name='Segment')
    op.drop_index('ix_Segment_cat', table_name='Segment')
    op.drop_index('ix_Segment_date_created', table_name='Segment')
    op.drop_index('ix_Segment_distance', table_name='Segment')
    op.drop_index('ix_Segment_elev_gain', table_name='Segment')
    op.drop_index('ix_Segment_end_point', table_name='Segment')
    op.drop_index('ix_Segment_start_point', table_name='Segment')
    op.create_index(op.f('ix_Stream_point'), 'Stream', ['point'], unique=False)
    op.drop_index('idx_Stream_point', table_name='Stream')
    """
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_index('idx_Stream_point', 'Stream', ['point'], unique=False)
    op.drop_index(op.f('ix_Stream_point'), table_name='Stream')
    op.create_index('ix_Segment_start_point', 'Segment', ['start_point'], unique=False)
    op.create_index('ix_Segment_end_point', 'Segment', ['end_point'], unique=False)
    op.create_index('ix_Segment_elev_gain', 'Segment', ['elev_gain'], unique=False)
    op.create_index('ix_Segment_distance', 'Segment', ['distance'], unique=False)
    op.create_index('ix_Segment_date_created', 'Segment', ['date_created'], unique=False)
    op.create_index('ix_Segment_cat', 'Segment', ['cat'], unique=False)
    op.create_index('ix_Segment_act_type', 'Segment', ['act_type'], unique=False)
    op.create_index('idx_Segment_start_point', 'Segment', ['start_point'], unique=False)
    op.create_index('idx_Segment_end_point', 'Segment', ['end_point'], unique=False)
    op.drop_index(op.f('ix_Activity_polyline'), table_name='Activity')
    """
    op.drop_column('Activity', 'polyline')
    """
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    op.create_table('Stream_LineString',
    sa.Column('ath_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('act_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('act_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('act_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('linestring', geoalchemy2.types.Geometry(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('act_id', name=u'act_id_pk')
    )
    op.create_table('Stream_HeatPoint',
    sa.Column('ath_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(), autoincrement=False, nullable=True),
    sa.Column('density', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grade', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('power', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cadence', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_Stream_Act_multipoint'), table_name='Stream_Act')
    op.drop_index(op.f('ix_Stream_Act_linestring'), table_name='Stream_Act')
    op.drop_index(op.f('ix_Stream_Act_ath_id'), table_name='Stream_Act')
    op.drop_index(op.f('ix_Stream_Act_act_id'), table_name='Stream_Act')
    op.drop_table('Stream_Act')
    """
    ### end Alembic commands ###
